services:
  website:
    build:
      context: .
      args:
        GIT_COMMIT_SHA: ${GIT_COMMIT_SHA:-unknown}
        GIT_COMMIT_MSG: ${GIT_COMMIT_MSG:-unknown}
    ports:
      - "4321:4321"
    restart: unless-stopped